version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
        back_net:
          aliases:
            - post_db
            - comment_db
  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${PORT_OF_SERVICE_INSIDE_CONTAINERS}:${PORT_OF_SERVICE_IN_HOSTS}/${NET_PROTOCOL}
    networks:
        front_net:
          aliases:
            - ui
  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
        front_net:
          aliases:
            - post_front
        back_net:
          aliases:
            - post_back
  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
        front_net:
          aliases:
            - comment_front
        back_net:
          aliases:
            - comment_back

  prometheus:
    image: ${USERNAME}/prometheus
    networks:
        front_net:
          aliases:
            - prometheus_front
        back_net:
          aliases:
            - prometheus_back
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
        back_net:
          aliases:
            - node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'


volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
