version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
        back_net:
          aliases:
            - post_db
            - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${PORT_OF_SERVICE_INSIDE_CONTAINERS}:${PORT_OF_SERVICE_IN_HOSTS}/${NET_PROTOCOL}
    networks:
        front_net:
          aliases:
            - ui
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
        front_net:
          aliases:
            - post
        back_net:
          aliases:
            - post
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
        front_net:
          aliases:
            - comment
        back_net:
          aliases:
            - comment
volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
